# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcbaf87db5d0f2be64f86530712bf9dc792a9fea7ac9dccd57be08f64270fe952cef891c1672838505321c5e933d2c7766cf503ebaf009c6122a01b620ef72ce

test:
  secret_key_base: 0fcc53c9a1eb4113758bbd35afdd449a9aff5861df4fc440a10d39795a64f2ff7f5eae71a7c83440d23973cfd9013297f6c4a5d18b066b1cc92e788e0638a48b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
